### ISSUE TITLE
Snow add fails when providing an invalid regex in the ignore file

### ISSUE THREAD

**Issue by daniellanner** [Snowtrack/SnowFS#104]
## Summary
SnowFS provides the ability to ignore files within the repository when executing snow commands. These files are determined by entering regular expressions (RegEx) in the `ignore` file. If these (RegEx) are invalid the command currently exits with a fatal exception.

## Expected
The current situation is not ideal. I propose either one of two options (examples refers to `snow add *` command):

**A) Complete command and print warning**
Clearly state that all files have been staged and print which line RegEx is invalid.

**B) Terminate command with error message**
Exit staging process and return an error indicating which RegEx is invalid.

Although both options have merit, I personally tend towards option B) to keep the state of the database intact. Please feel free to disagree with me, @seb-mtl.

**Comment by seb-mtl** [comment]
Probably solved by PR #106 in issue #105

**Comment by daniellanner** [comment]
Tested and can confirm the fix ✅ 
@seb-mtl , you are an extraordinary human being 😘 

Will close issue.
