### ISSUE TITLE
snow rm moves files to trashcan

### ISSUE THREAD

**Issue by daniellanner** [Snowtrack/SnowFS#111]
## Summary
The `snow rm` command is currently used to unstage files. Unfortunately it also moves files to the trashcan.

## Expectued Behaviour
The `snow rm` command should unstage files only.

## Side Note
This command is being reworked with Issue #90. This report is likely to be closed in conjunction with it.

**Comment by seb-mtl** [comment]
As currently implemented like `git rm` files are removed from the index and from the working directory
