### ISSUE TITLE
(JS-0352) Detected member access on any typed variables

### ISSUE THREAD

**Issue by seb-mtl** [snowtrack/snowfs#127]
## Description
Despite your best intentions, the `any` type can sometimes leak into your codebase. Member access on any typed variables is not checked at all by TypeScript, so it creates a potential safety hole, and source of bugs in your codebase. Example - The not-preferred way : ```ts declare const anyVar: …

## Occurrences
There are 511 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/Snowtrack/SnowFS/issue/JS-0352/occurrences/](https://deepsource.io/gh/Snowtrack/SnowFS/issue/JS-0352/occurrences/)

**Comment by carusooo** [comment]
It looks like this issue has been resolved, as the deepsource link doesn't show any instances of this, nor does `eslint`.

Can this be closed or am I misunderstanding the `invalid` label maybe?

**Comment by seb-mtl** [comment]
Indeed, the error is gone. Thanks for the update! Time to do some spring cleaning in the repo over the next couple of days.
