### ISSUE TITLE
(JS-0351) Detected calling an any type value

### ISSUE THREAD

**Issue by seb-mtl** [snowtrack/snowfs#128]
## Description
Despite your best intentions, the any type can sometimes leak into your codebase. The arguments to, and return value of calling an `any` typed variable are not checked at all by TypeScript, so it creates a potential safety hole, and source of bugs in your codebase. Example - The not-preferred …

## Occurrences
There are 410 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/Snowtrack/SnowFS/issue/JS-0351/occurrences/](https://deepsource.io/gh/Snowtrack/SnowFS/issue/JS-0351/occurrences/)

**Comment by carusooo** [comment]
It looks like this issue has been resolved, as the deepsource link doesn't show any instances of this, nor does `eslint`.

Can this be closed or am I misunderstanding the `invalid` label maybe?
