### ISSUE TITLE
When versioning SVG and other texty image files, leverage git

### ISSUE THREAD

**Issue by DaniellMesquita** [Snowtrack/SnowFS#151]

**Comment by seb-mtl** [comment]
Thanks for the feature request. Unfortunately this is currently out of scope for this project

**Comment by tony** [comment]
Thank you,

Any more details on why SVG isn't covered? I use it as an "open" format of sorts for vector art.

Due SVG not being binary? Product / Technical reasons?

**Comment by seb-mtl** [comment]
Hi @tony, you can absolutely use SVG with SnowFS as there are no file type limitations. The proposed idea was to use Git for certain file types under the hood to benefit from the optimizations that come with textual-based file types like SVG.

**Comment by DaniellMesquita** [comment]
@seb-mtl, consider re-opening?

**Comment by seb-mtl** [comment]
@DaniellMesquita  Would you be interested to work on this issue?
