### ISSUE TITLE
Make SnowFS an npm package

### ISSUE THREAD

**Issue by seb-mtl** [Snowtrack/SnowFS#208]
As the title described, we are looking for someone who can help us making a [npm](https://www.npmjs.com/) package out of SnowFS.

If you are interested to share your expertise on the topic and help out, you are more than welcome aboard :-)

**Comment by seb-mtl** [comment]
Update: snowtrack is now registered at npm @ https://www.npmjs.com/org/snowtrack

**Comment by nicdard** [comment]
Hi I would like to try to help here :)

**Comment by seb-mtl** [comment]
Cool, sounds great! Any particular field in this area you would like to contribute to?

**Comment by nicdard** [comment]
Hi would like to help with the configuration to start with :muscle:

**Comment by seb-mtl** [comment]
Awesome! Feel free to join on Discord and we go from there https://discord.gg/RDKPuH8dkA
