### ISSUE TITLE
Notification info

### ISSUE THREAD

**Issue by stilobique** [Snowtrack/SnowFS#236]
Hello,
isn't a big issue, however i'm try Snowtrack with one project ; and the Test Notification work, but not really elegant about the title popup, show **electron.app.Snowtrack**, and ordering the windows notification panel with this name. Can be improve i'm think :) . 

![mNMoiZenS6](https://user-images.githubusercontent.com/3066684/131213647-cd2790de-4f6c-4cef-88ad-9b7d0a6df077.jpg)
![4w6KljhWjK](https://user-images.githubusercontent.com/3066684/131213700-9390ec4f-5308-4c6d-9954-ace93b28ab5e.jpg)

**Comment by seb-mtl** [comment]
Hi @stilobique, Thanks a lot for your report! The next update is already finished but a fix will make it into October's release.

On that note, this GitHub repository is used exclusively for `SnowFS`, not `Snowtrack`.

`SnowFS` is the underlying core technology of `Snowtrack`. Please feel free to report any further issues in the Discord channel!

Merci! 😊
