### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by JVariance** [snowtrack/snowfs#270]
**Describe the bug**
I tried to update snowtrack to the recent version yesterday, but when I started the program it crashed immediately with an uncaught exception error.

**To Reproduce**
-

**Screenshots**
![grafik](https://user-images.githubusercontent.com/62245444/160273292-4f535595-90d6-4740-9c8e-be422fbc5a30.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro - 21H2 (Build 19044.1586)

**Additional context**
I tried to de- and reinstall Snowtrack, but got the same error. Even after installing version 0.9 again, it occured. I also removed snowtrack's folders from %appdata% and %localappdata% and tried to reinstall.

**Comment by seb-mtl** [comment]
Hi @JVariance, thanks a lot for the report! Is there anything unusual about your machine regarding USB drivers?

**Comment by JVariance** [comment]
It is indeed!
I have problems with USB since some weeks.

**Comment by seb-mtl** [comment]
Thanks for the confirmation! I will publish a test build here today that could fix the issue.

**Comment by seb-mtl** [comment]
@JVariance  Could you give this build a try? https://snowtrack.s3.amazonaws.com/snowtrack/Snowtrack%20Setup%200.10.61.exe

**Comment by JVariance** [comment]
Yep, this build works! 👍🏼

**Comment by seb-mtl** [comment]
That's awesome! We will publish a new update next week, that will also contain this fix.

**Comment by seb-mtl** [comment]
Fixed in Snowtrack 0.10.84
