### ISSUE TITLE
Will Snowtrack be FOSS ?

### ISSUE THREAD

**Issue by berserkwarwolf** [Snowtrack/SnowFS#34]
Will Snowtrack be free open source software like SnowFS ?

**Comment by seb-mtl** [comment]
Hi @berserkwarwolf, most technologies of Snowtrack will be part of the open-source community. Unfortunately there are no plans at the moment to make the entire Software open-source

**Comment by berserkwarwolf** [comment]
Thanks for clarifying. Wish you the best!

**Comment by seb-mtl** [comment]
Thank you! :-)
